version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.yaml:snakeyaml
    versions:
    - "1.27"
  - dependency-name: com.google.flogger:flogger
    versions:
    - 0.5.1
  - dependency-name: com.google.flogger:flogger-system-backend
    versions:
    - 0.5.1
