################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package install

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    tags: true

###################
### Environment ###
###################
env:
  global:
  - secure: EzFSn3mO4dT8QNmrSCJL6/1RBEAQXjSmWlvNb6fkwfPZ0IM/bh3VRiTAqX+LZ1Mx5jAnV+IJA8jx1cQiEtd/NdOCaqG9uKNxXy/HHIrGXygolibxcql1jiAI44yNMNOh/FIW/95dF5qzbEom+VTboYAmJKOcJ3zZvQZ9FVojfG+PqLZFmX6nxaJUe6hG2m+ukvxL7B1laQIA2+r1BTBbLdRp8KwpDZza/Ltp8Uzxk8oHqhg0GmalZN330RKrV5UnLqvtbv8DLPl+8m9BOupZYL07owW8Sla7FPkTRKFJ6Jhao64KUwm1d1/cgoTGJvVhVn7wX4I0dQ5pBPsziReFmCsww7fK9t2XZDC39hIcP49kGw/31F8iUTpJ10RcwhW/feXc977YArA4Of0gh3O3lLXaaQgwdgaS2AbTmRYrDX0OUOuRGyzFN3X5Q4pfspKc9tn+8uOZhToadmLvxDW6Aur5wVyW4f3aDC3fqJadiV6vWAhwH5u47BprlOZTzTQzbsZQDReYeQikxEMwBA5QQoo+78Y+FtKBewt7gwkpYAHR/HhfXGEUC9GbggLEur+XJsasWCEOe08hoQoOAP6ktqVVUhJk4fs20bmM4qqjM98ZUZtOta3ZfRYeCC2S1vpxFIY3czWZ3lSngzMcL8FjxFQwHDSPqOdtFMyWbSo0hpQ=
  - secure: mpmKnDiUMGQNmLpabvBnd0wL2YWkbO4VqwRVdk8UyWUfTXJwLuMMLr4yc2BLKNE1mY/+q1XaxTkT3rUcD7Ook96nmOlSzzkMrmtH8LwcOsovoyv8c1G2sVjy0BA7jNOYgCOLGuYuMuBvliKVWP8z+H9ORdnCXaQDBqdByqz7qdLFsZduT1juTfGonXWEfc3yIeeLg6I8QTyRzCdHIaoI0wtXtE+x1L3gC79DKV39Ixlew//GMs271pISBYG9tSFbA1oxZzYuPaerhRj0xxN0nrQmKajh7gG+i3DerD20MVa0pV4gXJARSqjvgH9fwiBk2rTG/HIztt501F5KYsiCsS7HO5pwBatHRLyLF91DnlbSb9egUP8q5tcUGSu9yImw4Y4p2X7PCiNQCApcUZlGyRnSg24v9MUUkJIpnYPrwlcq2CD2Ujfj5lLbraK6zCJkW22BRIj3LNldUwAiLAw8i4DchIChaQyppbfCp2/WcdBlYJfVHV1WpBJovtmY8iI+SKlsmxmoFTI4RXoqz2KmzvFbz4VClLAhDPjFAiGpjo8xX36FEVTAB4ma9iU7BNsDQth8GVixvRlh0gZuEpZm7K9CrYiiX99HYMZ0P9UOUOiRIWmZA6rMxOKrD3fWIyVy9QmSvEcUVcQge87fOqUbZrfNjtyo5y/1bGsK+AuIH24=
