################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package install

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    tags: true

###################
### Environment ###
###################
env:
  global:
  - secure: sqoDYBHK9bkTh9yEBwscVI7LDG/cvsKhWdoazGhVlgkboji3zD9EYA4gxo90Hy7fVUq6cQ67XzOrES31VkPyOu+OjpFHOpOk3B8mwtz4rOSyCdLx+/a6rVatdgSirrUUIJFKixTVw7W0IAaFNCNo3zhHRdo47avnSDW0AAb9gT5E9+9wFQMwK2aQzlsWcN0lnBlRjAIsCDqQvNWbJPd+Wu6SzzKOkTbsVLAWPv+cPCaPS31Oh8rl+e2bUpLAQxerdrkeHj54TsaDvNF97vf5WJbWjEgCOtEIhFEGsLldbilgLVARo8/Ad5K1T5Ac8oOPOJZRYc1QYV9vDZPVq2SyZEIi9Z5boba4dvPf4eMi0OjMfFcXYy/6/QOPdvQE2GWh4zKJtTdhgVVjs48HOJOFSj91H3Y616CkwDkZZc9Fug1Uaf2+FFmXP1bPSKAVUjLtLo7F8AUfL3dJZR7+WcnM31QErK8h6a/KlznHcXWXVXPHxWFWXpXPltTkfpcWu9tjrMBVfnhAc5Cdbcyygc75R/L0yLexNNVlf317NqcPdCLyGRcnLIVoZgvrZF0UvVuUnyTvUPteOPcUy0ANZyboZ5US3n8oxyHdWQsxUhd8mrjykjTUA4z/P3xAajhQ3TMsWDuxQOhlV/JfB7HpXhxPPbeCk8DpwoeE4CGSTARAd0A=
  - secure: jBd78AKcTJo40QrWn2lcuAZwMF1vWDkWuwUXkHtZcQnzqIyG6HTKAUf7pakPrU1EtxuDCuRSVwfcg/n/8MHDLFYCl2j4oWNORxqyUCA7t+KvAH4g4QGGehmM3UZXFZU+oez7k44tE19PQfPVcQSx705OFhI5tdeULFvkJAKsZYNv+ekmF1La+xfdavC2fKs8/sRvcBcrs/uRRGaPGGbeMyWhCMoejvKfbcc77LHPESu76KGawIq+0q/5u/f5DfHPHn1hx6TJ63luXoo0aqeXk9+IEdeMbSPqYjpBQCtPELAYOz54TL3701Azrscu1+o3pmkOH4SfIFeeR8/MZRaA8EhW7Pi0bPDvzn09bQj4nIGyFEJU7omADJUbdOx+qsUTXeDXWYVtMUdVw7WtYPd+/3W7p1KYTPk0V/n0tUbDAcyJJ/6/QhVPi2CCwiRwha8LlGQfL4Vwt1Df8n42tXgjTpkRc8oraxkVU2y5mGYXth4buXyIjk3q/fN3sVTAO4KoSy2nwnD5Ka1oZSO1OtEWKuQAy2v0Sm6BSoTSKJs5c0RjhVq18s/cTSXYwFgHJp3W4bcY8VoaIrejNbcx9RKvqnK9qVGoNdV7zAWfrKZLD8PQ82OIHkY+dmBhh6u8oRvlGhNm2jqKqxQCY8C97kU60mIRdo1aNzV7WGqbZ772mO8=
